config/routes.rb
Ddl::Application.routes.draw do
  resources :tags
  resources :games
  resources :sources
  resources :concepts
  #resources :documents do
  #  collection do
  #    get :links
  #    get :concepts
  #    post :save_judgment
  #    get :search
  #  end
  #  member do
  #    #get :start
  #    get :click
  #    get :show_in_frame
  #  end
  #end
  
  resources :users

  match 'documents' => 'documents#index'
  match 'documents/:id' => 'documents#show', :as => :item, :id => /\d+/
  match 'documents/:id/edit' => 'documents#edit', :as => :edit_document, :id => /\d+/
  match 'documents/start' => 'documents#start'
  
  match 'doctrack' => 'doctrack#index'
  match 'doctrack/:id' => 'doctrack#show', :as => :item, :id => /\d+/
  match 'doctrack/start' => 'doctrack#start'
  
  match 'items' => 'items#index', :as => :items
  match 'items/:id' => 'items#show', :as => :item, :id => /\d+/
  match 'items/:id/edit' => 'items#edit', :as => :edit_item, :id => /\d+/
  match 'items/:id/destroy' => 'items#destroy', :as => :del_item, :id => /\d+/
  match 'items/new' => 'items#new', :as => :new_item

  match ':controller/:action' => '#index'
  match '/:controller(/:action(/:id))'
end

app/models/source.rb
# Sources form which documents are collected
class Source < ActiveRecord::Base
  has_many :item
  serialize :option, Hash
  serialize :filter, Hash  
  scope :active, {:conditions=>{:active_flag=>true}}
  attr_accessor :last_sync_at
  
  def initialize
    @last_sync_at = nil
  end
  
  def o
    option || {}
  end
  
  
  def self.sync_interval_default()
    @sync_interval_default ||= Conf.collector_sync_interval
  end
  
  def sync_now?()
    return true if !@last_sync_at
    (Time.now - @last_sync_at > (sync_interval || Source.sync_interval_default))? true : false
  end
  
  def update_sync_content(content)
    hash_content =  content.to_md5
    if sync_content == hash_content
      #debug "[update_sync_content] Nothing to update!"
      false
    else
      #debug "[update_sync_content] #{sync_content.size} != #{content.size}"
      update_attributes(:sync_content => hash_content)
      true
    end
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  include ApplicationHelper
  # GET /sources
  # GET /sources.xml
  def index
    @sources = Source.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sources }
    end
  end

  # GET /sources/1
  # GET /sources/1.xml
  def show
    @source = Source.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @source }
    end
  end

  # GET /sources/new
  # GET /sources/new.xml
  def new
    @source = Source.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @source }
    end
  end

  # GET /sources/1/edit
  def edit
    @source = Source.find(params[:id])
  end

  # POST /sources
  # POST /sources.xml
  def create
    @source = Source.new(params[:source])

    respond_to do |format|
      if @source.save
        flash[:notice] = 'Source was successfully created.'
        format.html { redirect_to(@source) }
        format.xml  { render :xml => @source, :status => :created, :location => @source }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sources/1
  # PUT /sources/1.xml
  def update
    @source = Source.find(params[:id])

    respond_to do |format|
      if @source.update_attributes(params[:source])
        flash[:notice] = 'Source was successfully updated.'
        format.html { redirect_to(@source) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.xml
  def destroy
    @source = Source.find(params[:id])
    @source.destroy

    respond_to do |format|
      format.html { redirect_to(sources_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/sources/edit.html.erb
<h1>Editing source</h1>

<% form_for(@source) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :itype %><br />
    <%= f.text_field :itype %>
  </p>
  <p>
    <%= f.label :uri %><br />
    <%= f.text_field :uri %>
  </p>
  <p>
    <%= f.label :sync_at %><br />
    <%= f.date_select :sync_at %>
  </p>
  <p>
    <%= f.label :option %><br />
    <%= text_area_tag "source[option]", @source.option.to_yaml, :size=>'30x10' %>
  </p>
  <p>
    <%= f.label :active_flag %><br />
    <%= f.check_box :active_flag %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

app/views/sources/index.html.erb
<h1>Listing sources</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Dtype</th>
    <th>Uri</th>
    <th>Option</th>
    <th>Active</th>
  </tr>

<% @sources.each do |source| %>
  <tr>
    <td><%=h source.title %></td>
    <td><%=h source.itype %></td>
    <td><%=f source.uri, :limit=>20 %></td>
    <td><%=h source.active_flag %></td>
    <td><%= link_to 'Show', source %></td>
    <td><%= link_to 'Edit', edit_source_path(source) %></td>
    <td><%= link_to 'Destroy', source, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New source', new_source_path %>

app/views/sources/new.html.erb
<h1>New source</h1>
<%= form_for(@source) do |f| %>
	<% debugger %>
  	<%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :itype %><br />
    <%= f.text_field :itype %>
  </p>
  <p>
    <%= f.label :uri %><br />
    <%= f.text_field :uri %>
  </p>
  <p>
    <%= f.label :option %><br />
    <%= f.text_area :option %>
  </p>
  <p>
    <%= f.label :active_flag %><br />
    <%= f.check_box :active_flag %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', sources_path %>

app/views/sources/show.html.erb
<p>
  <b>Title:</b>
  <%= @source.title %>
</p>

<p>
  <b>Dtype:</b>
  <%= @source.itype %>
</p>

<p>
  <b>Uri:</b>
  <%= @source.uri %>
</p>

<p>
  <b>Option:</b>
  <%= simple_format @source.option.to_yaml %>
</p>

<p>
  <b>Active:</b>
  <%= @source.active_flag %>
</p>


<%= link_to 'Edit', edit_source_path(@source) %> |
<%= link_to 'Back', sources_path %>