config/routes.rb
Ddl::Application.routes.draw do
  resources :tags
  resources :games
  resources :sources
  resources :concepts
  #resources :documents do
  #  collection do
  #    get :links
  #    get :concepts
  #    post :save_judgment
  #    get :search
  #  end
  #  member do
  #    #get :start
  #    get :click
  #    get :show_in_frame
  #  end
  #end
  
  resources :users

  match 'documents' => 'documents#index'
  match 'documents/:id' => 'documents#show', :as => :item, :id => /\d+/
  match 'documents/:id/edit' => 'documents#edit', :as => :edit_document, :id => /\d+/
  match 'documents/start' => 'documents#start'
  
  match 'doctrack' => 'doctrack#index'
  match 'doctrack/:id' => 'doctrack#show', :as => :item, :id => /\d+/
  match 'doctrack/start' => 'doctrack#start'
  
  match 'items' => 'items#index', :as => :items
  match 'items/:id' => 'items#show', :as => :item, :id => /\d+/
  match 'items/:id/edit' => 'items#edit', :as => :edit_item, :id => /\d+/
  match 'items/:id/destroy' => 'items#destroy', :as => :del_item, :id => /\d+/
  match 'items/new' => 'items#new', :as => :new_item

  match ':controller/:action' => '#index'
  match '/:controller(/:action(/:id))'
end

app/controllers/documents_controller.rb
require 'ddl_include'

class DocumentsController < ApplicationController
  include AdminHelper, DocumentsHelper, ApplicationHelper
  before_filter :authorize, :except => [:login, :index, :show, :search, :click]
  before_filter :game_setup
  #before_filter :apply_user_level
  DL_TYPES = ['content','person','event','pubtime','caltime'].map{|e|e.to_sym}
  sidebar :pagehunt_search, :only=>[:index, :search]
  sidebar :menu, :only=>[:index]
  sidebar :pagehunt_status, :only=>[:show, :start_search, :search, :request_document]
  sidebar :pagehunt_relevant_concepts, :only=>:show, :if=>:item_concept?
  #sidebar :linked_concepts, :only=>[:show], :unless=>:item_concept?
  sidebar :pagehunt_scoreboard
  layout "doctrack"
  
  #sidebar :concept_cloud, :if=>:source_given?
  #sidebar :linked_concepts, :only=>:show
  #sidebar :linked_documents, :only=>:show
  
  def game_setup
    @display_topk =        15   #get_config("DISPLAY_TOPK_RESULT").to_i
    @pages_per_game =      10   #get_config("PAGES_PER_GAME").to_i
    @queries_per_page =    10   #get_config("QUERIES_PER_PAGE").to_i
    @no_entry_item    =    10
    @display_page_total =   2   #get_config("DISPLAY_PAGE_NO").to_i
    @time_per_page =       15   #get_config("TIME_PER_PAGE").to_i
    @ratio_game_type = {:s=>1}#{:sb=>0.5, :bd=>0.5}
    @user_level_applied = false
    $document_list ||= Item.valid.documents.all.group_by{|e|e.itype}.map_hash{|k,v|[k,v.map{|e|e.id}]}
    $concept_list  ||= Item.valid.concepts.all.map{|e|e.id}
  end
  
  # GET /documents
  # GET /documents.xml
  def index
    #info "What's wrong?"
    finish_game()
    @start_at = params[:start_at] || Time.now.years_ago(1).to_date.to_s
    @end_at = params[:end_at] || Date.tomorrow.to_s
    conditions = {}
    conditions.merge!({:itype=>params[:itype]}) if params[:itype] && !params[:itype].include?("all")
    conditions.merge!({:query_flag=>true}) if params[:query_only]
    @documents = Item.valid.searchables.between(@start_at, @end_at).paginate( :conditions=>conditions, :order=>"basetime desc", :page=>params[:page],:per_page=>50)
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @documents }
    end
  end
  
  # Start a new game
  def start
    @game = Game.create(:gid=>"#{session[:user_uid]}_#{Time.now.to_s(:db)}", 
      :user_id=>session[:user_id], :level=>session[:user_level], :start_at=>Time.now)
    init_game(@game.id)
    @query_docs_total = Item.documents.find_all_by_query_flag(true).map{|d|d.id}
    @query_cons_total = Item.concepts.find_all_by_query_flag(true).map{|d|d.id}
    @query_items_found = Query.find_all_by_user_id(session[:user_id]).map{|e|e.item_id}.uniq
    session[:query_cons] = @query_cons_total -  @query_items_found
    session[:query_docs] = @query_docs_total -  @query_items_found
    #debugger
  end
  
  # FInalize current game
  # - store game data
  def finish
    @game = Game.find(session[:game_id])
    @game.update_attributes(:score=>session[:score], 
      :query_count=>session[:total_query_count], :finish_at=>Time.now, :comment=>params[:comment])
    session[:query_count] = nil
    @comment = ""#"Did you find browsing helps you find items better?\n\n"
    if params[:comment]
      finish_game()
      redirect_to :controller=>:games 
    end
  end
  
  # User request a new document
  def request_document
    session[:total_query_count] += session[:query_count]
    if params[:skip] && session[:query_count] > 0
      session[:seen_doc_count] += 1
    end
    if game_finished? || params[:finish]
      redirect_to :action=>:finish
      return
    else
      init_target_document()
    end
  end
  
  # User start searching
  # - determine which document to find
  def start_search
    session[:document_index]  = rand(@display_page_total) if !session[:document_index]
    session[:target_document] = session[:display_docs][session[:document_index]].to_i
    itype_target_document = Item.find(session[:target_document]).itype
    @relevant_position = -1
    case session[:game_type]
      when:bc
        @items = Item.find($concept_list.sample(@no_entry_item).uniq - session[:display_docs])
        render :start_browse
      when:bd
        @items = Item.find($document_list[itype_target_document].sample(@no_entry_item).uniq - session[:display_docs])
        render :start_browse
    end
  end
      
  # Process search action
  # - add query as document
  def search
    @query = params[:query].gsub(/[\'\"]/, "")
    info "Query : #{@query}"
    @query_did = [get_user_id(),@query].join(" ").to_id
    
    @search_results = SolrSearcher.new.search_by_keyword( @query, :doc_only=>true, :raw=>true)#[display_range(params[:page])]#search_remote('k', @query)
    if !@search_results
      flash[:notice] = "Invalid query!"
      if !during_game?
        redirect_to :action=>:search 
      elsif query_limit_reached?
        redirect_to :action=>:request_document, :skip=>true    
      else
        redirect_to :action=>:start_search 
      end
      return
    end
    #debugger
    @rank_list = @search_results.hits.map{|e|{:item=>e.instance, :id=>e.instance.id, :score=>e.score}}
    @query_doc = Item.find_or_create(@query, 'query', :did=>@query_did, 
      :uri=>request.url, :content=>@rank_list.map{|e|e[:item].title}.join("\n")) 
    if during_game?
      process_search_result(@rank_list.map{|e|e[:id]}, @query_doc.id, @query)
    end
  end
  
  # Judge rank list and change status
  # @arg rank_list : ranked list of document ids
  def process_search_result(rank_list, query_id, query_text = nil)
    @relevant_position = -1
    rank_list.each_with_index do |e,i|
      @relevant_position = i+1 if session[:target_document].to_i == e
    end
    Query.create(:query_text=>query_text, :query_id=>query_id, :position=>@relevant_position, :query_count=>session[:query_count],
      :item_id=>session[:target_document], :user_id=>session[:user_id], :game_id=>session[:game_id])
    session[:query_count] += (query_text ? query_text.split(/\s+/).size : 1 ) if session[:query_count]
    if page_found? || query_limit_reached?
      session[:seen_doc_count] += 1
      if page_found?
        session[:score] += (@display_topk.to_f / @relevant_position / 1.5 ).to_i
        #session[:score] += (@display_topk.to_f / @relevant_position / 3 ).to_i + ((@queries_per_page - session[:query_count] + 1) / 2).to_i
      end
    end
  end
  
  # GET /documents/1
  # GET /documents/1.xml
  def show
    if params[:random]
      if @display_page_total <= session[:display_page_cur] 
        redirect_to :action=>:start_search
        return
      end
      #debugger
      if session[:game_type] == :b
        #$concept_list.sample[0]
        params[:id] = session[:query_cons].sample#[0]
        session[:query_cons] -= [params[:id]]
      else
        params[:id] = session[:query_docs].sample#[0]
        session[:query_docs] -= [params[:id]]
      end
      #puts params.inspect, session.inspect
      session[:display_page_cur] += 1
      session[:display_docs] << params[:id].to_i
      #History.create(:htype=>"show", :basetime=>Time.now, :src_item_id=>session[:game_id], :item_id=>params[:id], :user_id=>get_user_id(),
      #  :metadata=>{:url=>request.url})
      #debug "#{session[:display_page_cur]} < #{@display_page_total} (#{session[:display_docs].inspect})"
      @item = Item.find(params[:id])
    else
      @item = Item.find(params[:id])
      $items = {}
      begin
        if @item.itype == 'concept'
          @rel_docs = (search_local('kwd', "\"#{@item.title}\"", :doc_only=>true) || [])[display_range(params[:page])]
          @search_type, @feature_type, @htype = 'con', Searcher::CON_FEATURES, 'con'
          @rel_cons = (search_local(@search_type, params[:id]) || [])[display_range(params[:page])]
        else
          @search_type, @feature_type, @htype = 'doc', Searcher::DOC_FEATURES, 'doc'        
          @rel_docs = (search_local(@search_type, params[:id]) || [])[display_range(params[:page])]
        end
        #info "Ranklist(doc) : #{@rel_docs.inspect}"
        #debugger
      rescue Exception => e
        error "Failed to get Ranklist!", e
        @rel_docs = @rel_cons = []
      end
      if during_game?
        process_search_result(@rel_docs.map{|e|e[:id]}, params[:id])
      end
    end
    
    @link_docs, @link_cons = [], []
    @item.link_items.uniq.each do |e|
      (e.concept?)? (@link_cons << e) : (@link_docs << e)
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @item }
    end
  end
  
  # Show textual content of the document (for back-up)
  def show_content
    @document = Item.find(params[:id])
    render :action=>:show_content, :layout=>"content_only"
  end
  
  # Process & log user click
  # - Add to history
  # - Add to concept occurrence (for con<->doc click)
  # - Add to concept relation (for con<->con click)
  # - Add to document relation (for doc<->doc click)
  def click
    #debug(params)
    src_item, tgt_item = params[:src_item_id].to_i, params[:id].to_i
    History.create(:htype=>params[:htype], :basetime=>Time.now, :src_item_id=>session[:target_document], :item_id=>tgt_item, :user_id=>get_user_id(),
      :game_id=>session[:game_id], :metadata=>{:real_src_item_id=>src_item, :position=>params[:position], :url=>request.url})
    Link.find_or_create(src_item, tgt_item, 'c', :add=>1)
    redirect_to :action=>:show
  end

  # GET /documents/new
  # GET /documents/new.xml
  def new
    @document = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Item.find(params[:id])
  end

  # POST /documents
  # POST /documents.xml
  def create
    @document = Item.new(params[:document])

    respond_to do |format|
      if @document.save
        flash[:notice] = 'Document was successfully created.'
        format.html { redirect_to(@document) }

app/helpers/documents_helper.rb
module DocumentsHelper  
  #def select_for_itype(default)
  #  options = ['all','calendar','file','email','webpage','news','blog','concept'] #'paper',
  #  select_tag(:itype, options_for_select(options.map{|e|[e,e]},default), 
  #    :multiple=>true, :onchange => 'this.form.submit()')
  #end
  
  def user_level()
    session ? session[:user_level].to_i : 0
  end
  
  def user_level_new(score)
    if score >= 75 : 2
    elsif score >= 50 : 1
    else
      0
    end
  end
  
  def apply_user_level
    return if @user_level_applied
    @queries_per_page -= user_level * 2
    @no_entry_item -= user_level * 2
    @display_page_total += user_level
    @user_level_applied = true
  end
  
  def update_user_level(score)
    session[:user_level] = user_level_new(score)
    User.find(session[:user_id]).update_attributes!(:level=>user_level_new(score))
  end
  
  def display_user_list(level)
    User.find_all_by_level(level).map{|e|(e.id == session[:user_id])? "<b>#{e.uid}</b>" : e.uid}.join(" ")
  end
  
  def display_game_type()
    case session[:game_type]
    when :s : "Searching"
    when :sb : "Searching+Browsing"
    when :bc : "Browsing"      
    when :bd : "Browsing"      
    end
  end
  
  def display_range(param_page)
    page = (param_page || 1).to_i
    ((page-1) * @display_topk)..(page * @display_topk-1)
  end
  
  # Display link URL for clickthrough recording
  # - query is the target item for game instead of the current item
  def display_link(item, rank_list, htype, position)
    if during_game?
      if session[:game_type] != :s && !page_found? && !query_limit_reached?
        link_to item.title, {:action=>'click', :htype=>htype, :id=>item.id, :src_item_id=>session[:target_document], 
          :position=>(position+1), :skipped_items=>rank_list[0..position].reverse.join("|")}, :title=>'Click to see more items like this!'
      else
        item.title
      end
    else
      link_to item.title, {:action=>'show', :id=>item.id}
    end
  end
  
  def redirect_to_after(url , second)
    "<meta http-equiv='refresh' content='#{second};url=#{url}'>"
  end
    
  # Initialize per-game variable
  def init_game(game_id)
    session[:game_id] = game_id
    session[:total_query_count] = 0 # #queries in overall
    session[:seen_doc_count] = 0
    session[:score] = 0
    session[:query_count] = 0
    session[:display_page_cur] = 0
    #init_target_document()
  end
  
  def finish_game()
    session[:game_id] = nil
  end
  
  # Initialize per-document variable
  def init_target_document()
    session[:query_count] = 0
    #session[:refresh_count] = 3
    session[:display_page_cur] = 0
    
    session[:display_docs] = []
    session[:document_index] = nil
    
    session[:game_type] = @ratio_game_type.dice[0]
  end
  
  def during_game?
    session[:game_id]
  end
  
  def page_found?
    puts "#@relevant_position <= #@display_topk"
    @relevant_position <= @display_topk && @relevant_position > 0
  end
  
  def query_limit_reached?
    during_game? && session[:query_count] >= @queries_per_page
  end
  
  def game_finished?
    session[:seen_doc_count] && session[:seen_doc_count] >= @pages_per_game
  end
  
  def source_given?
    params && params[:source]
  end
end

app/views/documents/_search_result.html.erb
<% if during_game? %>
<h3>
	<% if game_finished? %>
		<%= raw "Game Finished! #{link_to 'Click here', :action=>:request_document, :finish=>true} to see the score." %>
	<% elsif page_found? %>
		<%= raw "Item Found! #{link_to 'Click here', :action=>:request_document} to see the next item." %>
	<% elsif query_limit_reached? %>
		<%= raw "Query limit reached! #{link_to 'Click here', :action=>:request_document} to see the next item." %>
	<% else %>
		<%= raw "Item Not Found! You have #{@queries_per_page - session[:query_count]} trials left." %>
		<br>
		<% if session[:game_type] != :bc && session[:game_type] != :bd %>
			<% form_tag({:controller=>'documents',:action => 'search'}, :method => :get) do -%>
				<%= text_field_tag(:query, @query, :onpaste=>'return false;', :size=>60) %>
				<%= submit_tag('Search') %>
			<% end -%>
		<% end %>
		<% if controller.action_name == 'show' %>
		<br>You can <%= raw link_to "skip", :action=>:request_document, :skip=>true%>  to the next item or <a href="javascript: history.go(-1)">move back</a> to the previous page.
		<% else %>
		<br>You can <%= raw link_to "click here", :action=>:request_document, :skip=>true%> to skip  to the next item.
		<% end %>
	<% end %>
</h3>
<br>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<% form_for(@document) do |f| %>
  <%= f.error_messages %>
  <p>
    <strong><%= f.label :title %></strong><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <a href='<%= @document.uri  %>'><%= @document.uri  %></a><br />
  </p>
  <p>
   <strong> <%= f.label :content %></strong><br />
    <% if @document.uri =~ /^http/ %>
			(click <%= link_to "here", {:action=>:show_content, :id=>@document.id}, :target=>'iframe_doc' %> to see the text if the content is invisible)
			<iframe name='iframe_doc' src="<%= display_url(@document.uri) %>" width="750" height="780" style="border: none;"></iframe>
		<% else %>
			<%= @document.content.gsub("\n","<br/>") if @document.content %>
		<% end %>
  </p>
	<p>
	  <b>Queries:</b> <br>
		<table border='1' cellspacing=0 cellpadding=2>
		<tr><td><strong>User</strong></td><td><strong>Query</strong></td><td><strong>Rank(order)</strong></td></tr>
	  <%= Query.find_all_by_item_id(@document.id).map{|e|"<tr><td>#{e.user.uid}</td><td>#{e.query_text}</td><td>#{e.position}(#{e.query_count})</td></tr>"}.join("\n") %>
		</table>
	</p>
  <p>
    <strong><%= f.label :query_flag %></strong><br />
    <%= f.check_box :query_flag %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/finish.html.erb
<h1>Game Statistics </h1>
<% score = session[:score].to_i %>
<h2>Score : <%= score %></h2>
<h2>Queries Issued : <%= session[:total_query_count] %></h2>
<h2>Time Spent : <%= (@game.finish_at - @game.start_at).round %> seconds</h2>
<% if user_level < user_level_new(score) %>
<br>
<h3>Congratulations! You moved to level <%= user_level_new(score) %>!  </h3>
<br>
<% update_user_level(score) %>
<% end %>

<h3>Do you feel that browsing to related item was helpful in finding things? <br> In what way? If not, why?  (any other feedback will be appreciated.)</h3>

<% form_tag({:controller=>'documents',:action => 'finish'}, :method => :post) do -%>
<%= text_area_tag(:comment, @comment, :cols=>80, :rows=>10, :value=>@comment) %><br>
<%= submit_tag('Submit Feedback') %> (you'll be redirected to the scoreboard after submission)
<% end -%>

app/views/documents/index.html.erb
<h1>Welcome to DocTrack game!</h1>
This is a collection of documents of many types (calendar, file, email, webpage and news) that may be found in the desktop of a typical UMass CS grad student. <br>
<br>Please imagine that this is your new desktop and try browsing or searching it for a while. Use the sidebar to filter the documents by type.
<h3>Click <%= link_to "here", :action=>:start %>  to start a new game when you're ready.</h3>
<table  class="sortable" id="sortabletable">
  <tr>
  </tr>

<% @documents.each do |document| %>
  <tr>
    <td><%= @ranklist.to_hash[document.did] %></td>
    <td><%= document.itype %></td>
    <td><%= link_to document.title, :controller=>:documents, :action=>:show, :id=>document.id, :title=>document.to_s %></td>
<% if session[:admin_flag] %>
    <td><%= document.query_flag ? "(#{Query.find_all_by_item_id(document.id).size})" : "" %></td>
    <td><%= link_to 'Edit', edit_document_path(document) %></td>
    <td><%= link_to 'Del', document, :confirm => 'Are you sure?', :method => :delete %></td>
<% end %>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate(@documents) if @documents.respond_to?("total_pages")%>

app/views/documents/request_document.html.erb
<h1>Request Document</h1>

<h2>You'll see new document soon.</h2>
<% if session[:seen_doc_count] > 0 %>
	<h3>You have found <%= session[:seen_doc_count] %> documents so far. </h3>
<% end %>
<h3>If you're impatient, <%= link_to("click here", :action=>:show, :random=>true)%>.</h3>
<%= raw redirect_to_after(url_for(:action=>:show, :random=>true), 2) %>
<table>
  <tr>
  </tr>
</table>

<br />

app/views/documents/search.html.erb
<h1>Search Result ( <%= @query %>)</h1>
<%= render :partial => "search_result" %>

<% debug(session)%>
<table>
  <tr>
  </tr>

<% @rank_list.each_with_index do |e,i| %>
  <tr>
    <td><%= i+1 %></td>
    <td><%= e[:item].itype %></td>
    <td><%= link_to(e[:item].title, {:action=>'show', :id=>e[:item].id}) %></td>
    <td><%= raw "<font color='#ff0000'>target document!</font>" if e[:item].id == session[:target_document].to_i %></td>
  </tr>
<% end %>
</table>
<% if during_game? && !page_found? && !query_limit_reached? %>
<h3> Click each document to browse into related document!</h3>
<% end %>
<br />

app/views/documents/show.html.erb
<% if params[:random] %>
	<h2>Here's the <%= session[:display_page_cur].to_i.ordinalize %> (out of <%= @display_page_total %>) item (
	<% if @display_page_total <= session[:display_page_cur] %>
		 <%= link_to("skip to search", :action=>:start_search)%> 
	<% else %>
	 <%= link_to("skip to next", :action=>:show, :random=>true)%> 
	<% end%>
	)</h2>
<% else %>
	<%= render :partial => "search_result" %>
<% end %>
<% debug session%>
<%= raw "<b>Did: </b>" + @item.did if session[:admin_flag] && @item.did %>

<p>
  <b>Title:</b>
  <%= @item.title %> <%= @item.query_flag ? "(query)" : "" %>
</p>
<% if @item.uri =~ /^http:/ %>
<p>
  <b>URL:</b>
  <%= link_to @item.uri, @item.uri %>
</p>
<% end %>
<% if @item.metadata %>
<p>
  <b>Metadata:</b> <br>
	<table border='1' cellspacing=0 cellpadding=2>
  <%= raw @item.metadata.find_all{|k,v|!v.blank?}.map{|e|"<tr><td>#{e[0]}</td><td>#{e[1]}</td></tr>"}.join("\n") %>
	</table>
</p>
<% end %>
<% if @rel_docs %>
	<b>Relevant Items:</b>
	<br>(click a link below to <b>browse</b> into other item!)
	<table border=0 cellpadding=2 cellspacing=0>
	<% if @item.itype != 'concept' %>
		<% @rel_docs[0..(@display_topk-1)].each_with_index do |e,i| %>
			<% item = cache_data("item_#{e[:id]}") %>
			<% error "#%%%%% : "+item.did %>
			<tr>
			  <td><%= i+1 %></td>
			  <td><%= item.itype %></td>
			  <td><%= raw display_link(item, @rel_docs.map{|e2|e2[:id]}, @htype, i) %></td>
			  <td><%= item.tag_titles[0..3].join(",") %></td>
			<% if Conf.debug || params[:debug] %>
				<%=[:score].concat(@feature_type).map{|f|"<td>#{(e[f]||0).to_f.r3}</td>"} %>
			<% end %>
			<td><%= "<font color='#ff0000'>target item!</font>" if item.id == session[:target_document].to_i %></td>
			</tr>
		<% end %>
	<% else %>
		<% @rel_docs.each_with_index do |e,i| %>
		  <tr>
		    <td><%= i+1 %></td>
		    <td><%= e[:item].itype %></td>
		    <td><%= display_link(e[:item], @rel_docs.map{|e2|e2[:id]}, 'doc', i) %></td>
		    <td><%= "<font color='#ff0000'>target document!</font>" if e[:id] == session[:target_document].to_i %></td>
		  </tr>
		<% end %>
	<% end %>
	</table>
<% end %>
<p>
  <b>Content:</b> <br>
	(click <%= link_to "here", {:action=>:show_content, :id=>@item.id}, :target=>'iframe_doc' %> to see the content if it's invisible)
		<iframe name='iframe_doc' src="<%= display_url(@item) %>" width="700" height="780" style="border: none;"></iframe>
</p>

app/views/documents/show_content.html.erb
<%= raw @document.content.gsub("\n","<br/>") if @document.content %>

app/views/documents/start.html.erb
<h1>Start a New Game</h1>

<h2>Goal</h2>
Your goal is to find the documents you're shown using the search engine provided. Since finding the document you've just seen is too easy, we show <%= @display_page_total %> documents in a row and tell you which document to find in the end. <br><br>

Your score is determined by where in the Top <%= @display_topk_result %> rank list you can locate the target document. For instance, if the target document was found at the first rank, you can get 10 points.<br><br>


<h2>Rules</h2>
- You'll be finding <%= @pages_per_game %> documents per game, each of which will be provided with <%= @display_page_total-1 %> other documents. <br>

- You'll be given <%= @time_per_page %> seconds to skim each document after it's loaded.<br>

- Please do not copy and paste document text. (pasting to search box is disabled) <br>

- The search engine used for this game indexes everything (type, title, uri, metadata and content) shown in the document page.

- The search engine handles only simple keyword queries without fancy features. (e.g. phrase, spell correction, etc.)

	<h3><%= link_to("Click here", :action=>:request_document)%> if you want to start now!</h3>

app/views/documents/start_browse.html.erb
<h1>Start Browsing</h1>
<h2>Your job is to find the <%= (session[:document_index]+1).to_i.ordinalize %> item.</h2>
<h3>Start from one of the given items! <%= "You have #{@queries_per_page - session[:query_count]} trials left." %></h3>
<br>

<table border=1 cellspacing=0 cellpadding=2>
  <tr>
		<td><strong>Title</strong></td>
		<td><strong>Linked Concepts</strong></td>
  </tr>
	<% @items.each_with_index do |c,i|%>
  <tr>
		<td><%= display_link(c, @items.map{|e|e.id}, "doc", i) %></td>
		<td><%= c.link_cons[0..2].map{|e|link_to e.title, :action=>:show, :id=>e.id}.join(" ") %></td>
  </tr>
	<% end %>
</table>

<br>

<h3>You can refresh the browser if you don't like these items. <br> Or you can <%= link_to "click here", :action=>:request_document, :skip=>true%> to skip to the next item without penality.</h3>
<% debug(session)%>

app/views/documents/start_search.html.erb
<h1>Start Search<%=" / Browsing" if session[:game_type] == :sb %></h1>
<h2>Your job is to find the <%= (session[:document_index]+1).to_i.ordinalize %> document.</h2>
<h3>Use search box here to find it! <%= "You have #{@queries_per_page - session[:query_count]} trials left." %></h3><br>
<% debug session%>

<% form_tag({:controller=>'documents',:action => 'search'}, :method => :get) do -%>
<%= text_field_tag(:query, @query, :onpaste=>'return false;', :size=>60) %>
<%= submit_tag('Search') %>
<br>(Each <u>keyword</u> is counted as one trial.)
<% end -%>

<h3>Or you can <%= link_to "click here", :action=>:request_document, :skip=>true%> to skip to the next document without penality.</h3>
<% debug(session)%>

<table>
  <tr>
  </tr>
</table>

<br />