config/routes.rb
Ddl::Application.routes.draw do
  resources :tags
  resources :games
  resources :sources
  resources :concepts
  #resources :documents do
  #  collection do
  #    get :links
  #    get :concepts
  #    post :save_judgment
  #    get :search
  #  end
  #  member do
  #    #get :start
  #    get :click
  #    get :show_in_frame
  #  end
  #end
  
  resources :users

  match 'documents' => 'documents#index'
  match 'documents/:id' => 'documents#show', :as => :item, :id => /\d+/
  match 'documents/:id/edit' => 'documents#edit', :as => :edit_document, :id => /\d+/
  match 'documents/start' => 'documents#start'
  
  match 'doctrack' => 'doctrack#index'
  match 'doctrack/:id' => 'doctrack#show', :as => :item, :id => /\d+/
  match 'doctrack/start' => 'doctrack#start'
  
  match 'items' => 'items#index', :as => :items
  match 'items/:id' => 'items#show', :as => :item, :id => /\d+/
  match 'items/:id/edit' => 'items#edit', :as => :edit_item, :id => /\d+/
  match 'items/:id/destroy' => 'items#destroy', :as => :del_item, :id => /\d+/
  match 'items/new' => 'items#new', :as => :new_item

  match ':controller/:action' => '#index'
  match '/:controller(/:action(/:id))'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :occurrences , :dependent => :destroy
  has_many :items, :through => :occurrences
  #has_and_belongs_to_many :items
  attr_accessor :occurrence_count
  
  scope :valid, {:conditions=>{:hidden_flag=>false}}
  scope :unmodified, {:conditions=>{:modified_flag=>false}}
  
  # Initialize new tag
  def self.find_or_create(title)
    #debugger
    tid = title.to_id
    tag = Tag.find_or_initialize_by_tid(tid)
    tag.update_attributes!(:title=>title, :tid=>tid)
    tag
  end
  
  #def self.find_by_tids( tids )
  #  all(:conditions=>{:tid=>tids})
  #end
  
  def self.find_by_source(source_id = nil)
    cond = source_id ? {:sources=>{:id=>source_id}} : {}
    all(:joins=>{:occurrences=>{:item=>:source}}, :conditions=>cond)
  end
  
  def invalidate
    update_attributes!(:hidden_flag=>true,:modified_flag=>true)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  #<%= in_place_editor_field "concept", "title", {}, {:load_text_url=> url_for(:action=>"get_concept_title", :id=>concept) } %>
  #in_place_edit_for :concept, :title
    # GET /concepts
  # GET /concepts.xml
  def index
    @tags = Tag.valid.find_by_source(params[:source]).group_by{|c|c}.
      map{|k,v|k.occurrence_count = v.size;k}.sort_by(&:occurrence_count).reverse

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @concepts }
    end
  end

  # GET /concepts/1
  # GET /concepts/1.xml
  def show
    @tag = Tag.find(params[:id])
    
    @items = @tag.items.uniq.sort_by(&:basetime).reverse
        
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tag }
    end
  end
  
  def click
    #debug(params)
    process_click(params)
    if params[:skipped_items].split("|").size > 1
      search_remote('c', "#{params[:src_item_id]}|#{params[:skipped_items]}", :jtype=>'log')
    end
    redirect_to :action=>:show
  end

  # GET /tags/new
  # GET /tags/new.xml
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.xml
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        flash[:notice] = 'Tag was successfully created.'
        format.html { redirect_to(@tag) }
        format.xml  { render :xml => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.xml
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag].merge(:modified_flag=>true))
        flash[:notice] = 'Tag was successfully updated.'
        format.html { redirect_to(@tag) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.xml
  def destroy
    @tag = Tag.find(params[:id])
    @tag.invalidate

    respond_to do |format|
      format.html { redirect_to(tags_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tag_helper.rb
module TagHelper
  # Create tags & links
  # @param titles [String] comma-separated string of tags
  # @param otype [String] type of occurrences
  def add_tags(titles, otype = "t")
    tags = sanitize_input(titles).map{|t|Item.find_or_create(t.strip, 'tag')}    
    #debug "[add_tags] titles = [#{titles}] otype = #{otype} (#{@tag_titles})"
    tags.each{|c|Link.find_or_create(self.id, c.id, otype)}
  end
  
  def sanitize_input(titles)
    if titles.class == String
      titles.split(",").find_all{|e|!e.blank?}
    else
      titles
    end
  end
  
  def clear_tags()
    occurrences.clear
  end
  
  # Replace existing tags with given tags
  def replace_tags(titles, otype = 't')
    clear_tags()
    add_tags(titles, otype)
  end
  
  # Read tag titles & update cache
  def tag_titles(otype = 't')
    if tags_saved
      tags_saved.split(",")
    else
      cond = otype ? {:links=>{:otype=>otype, :in_id=>id}} : {:links=>{:in_id=>id}}
      result = Item.all(:joins=>{:links=>:item}, :conditions=>cond).map(&:title)
      update_attributes!(:tags_saved=>result.join(","))
      result
    end
  end
  
  def tagged_with?(tag)
    tag_titles.split(",").include?(tag)
  end
end

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<% form_for(@tag) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>
<% content_for :left do %>
	<h3>By Source:</h3>
	<% debug(params)%>
	<% form_tag '', :method => 'GET'do %> 
		<% options = options_for_select([['all',-1]].concat(Source.active.map{|e|[e.title, e.id]}),params[:source] ? params[:source].map{|e|e.to_i} : [-1]) %>
		<%= select_tag(:source, options, :onchange => 'this.form.submit()')%>
	<% end %> 
<% end %>
<table class="sortable" id="sortabletable">
  <tr>
    <th>Title</th>
    <th class="sorttable_numeric">Occurrences</th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= link_to tag.title, tag %></td>
    <td><%=h tag.occurrence_count %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Del', tag, :method => :delete %></td>
		<td><%= link_to 'ToConcept', :controller=>:items, :action=>:create_concept, :source_id=>tag, :source_type=>'Tag' %></td>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate(@documents) if @tags.respond_to?("total_pages")%>
<%= link_to 'New tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<% form_for(@tag) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :cid %><br />
    <%= f.text_field :cid %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p>
  <b>Title:</b>
  <%=h @tag.title %>
</p>

<p>
  <b>Metadata:</b>
  <%=h @tag.metadata %>
</p>

<table  class="sortable" id="sortabletable">
  <tr>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td width='80'><%= item.basetime.to_date %></td>
    <td><%= item.itype %></td>
    <td><%= link_to item.title, item_path(item), :title=>item.to_s %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Del', del_item_path(item) %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'To Concept', :controller=>:items, :action=>:create_concept, :source_id=>@tag, :source_type=>'Tag' %> |
<%= link_to 'Back', tags_path %>