config/routes.rb
Ddl::Application.routes.draw do
  resources :tags
  resources :games
  resources :sources
  resources :concepts
  #resources :documents do
  #  collection do
  #    get :links
  #    get :concepts
  #    post :save_judgment
  #    get :search
  #  end
  #  member do
  #    #get :start
  #    get :click
  #    get :show_in_frame
  #  end
  #end
  
  resources :users

  match 'documents' => 'documents#index'
  match 'documents/:id' => 'documents#show', :as => :item, :id => /\d+/
  match 'documents/:id/edit' => 'documents#edit', :as => :edit_document, :id => /\d+/
  match 'documents/start' => 'documents#start'
  
  match 'doctrack' => 'doctrack#index'
  match 'doctrack/:id' => 'doctrack#show', :as => :item, :id => /\d+/
  match 'doctrack/start' => 'doctrack#start'
  
  match 'items' => 'items#index', :as => :items
  match 'items/:id' => 'items#show', :as => :item, :id => /\d+/
  match 'items/:id/edit' => 'items#edit', :as => :edit_item, :id => /\d+/
  match 'items/:id/destroy' => 'items#destroy', :as => :del_item, :id => /\d+/
  match 'items/new' => 'items#new', :as => :new_item

  match ':controller/:action' => '#index'
  match '/:controller(/:action(/:id))'
end

app/models/item.rb
#require 'searcher/more_like_this'

class Item < ActiveRecord::Base
  include TagHelper, IndexHelper
  include MetadataHelper, RuleHelper, MarkupHelper
  ITYPE_CONCEPT = ['concept','person']
  ITYPE_DOCUMENT = ['webpage','bookmark_webpage','email','email_memo','paper','blog','tweet','pub']
  #ITYPE_QUERY = ['concept','person']
  
  belongs_to :source
  has_many :inlinks, :foreign_key=>'in_id', :class_name=>'Link'
  has_many :initems, :through=>:inlinks
  has_many :outlinks, :foreign_key=>'out_id', :class_name=>'Link'
  has_many :outitems, :through=>:outlinks

  has_many :occurrences , :dependent => :destroy
  has_many :tags, :through => :occurrences # @todo : use links instead of occurrences?
  #has_and_belongs_to_many :tags

  has_many :links , :dependent => :destroy
  has_many :items, :through => :links
  
  serialize :metadata, Hash

  alias_attribute :m, :metadata
  alias_attribute :date_published, :basetime

  attr_accessor :score
  
  named_scope :between, lambda{|start_at, end_at| {:conditions=>
    ["basetime >= ? and basetime < ?", start_at, end_at]}}
    
  named_scope :itype, lambda{|itype| {:conditions=>
      ((itype=='all')? [] : ["itype = ?", itype])}}
  
  named_scope :valid, {:conditions=>{:hidden_flag=>false}}

  named_scope :unmodified, {:conditions=>{:modified_flag=>false}}
  
  named_scope :indexed, {:conditions=>["textindex is not null"]}
  
  named_scope :concepts, {:conditions=>{:itype=>'concept'}}
  named_scope :queries, {:conditions=>{:itype=>['query']}}
  named_scope :documents, {:conditions=>["itype != ? and itype != ?",'query', 'concept']}
  named_scope :searchables, {:conditions=>["itype != ?",'query']}
  
  # Sunspot/Solr search indexing  
  searchable do
    text :title, :content, :uri, :itype, :metadata, :id
    string :hidden_flag
    string :itype_str do
      itype.to_s.squeeze.downcase
    end
    #more_like_this :title, :content, :uri, :itype
  end

  def title
    (read_attribute(:title).blank?)? 'Untitled' : read_attribute(:title)
  end
  
  def concept?
    ITYPE_CONCEPT.include?(itype)
  end
  
  def document?
    !['concept','person','query'].include?(itype)#ITYPE_DOCUMENT.include?(itype)
  end
  
  def link_items
    #[inlinks.map{|l|[l, l.initem]}, outlinks.map{|l|[l, l.outitem]}].collapse
    [initems,outitems].flatten
  end
  
  def link_cons
    link_items.find_all{|e|e.concept?}
  end
  
  def con_titles
    link_cons.uniq.map{|e|e.title}
  end

  def link_docs
    link_items.find_all{|e|e.document?}
  end

  def links
    [inlinks,outlinks].flatten
  end
      
  def to_s(verbose = false)
    result = "#{title} [#{id}:#{itype}] "##{basetime.to_s(:db) if basetime}
    result += "\n#{metadata.inspect}\n#{uri}\n#{content[0..1000]}" if content && verbose
    result
  end
  
  # Return if the content is actually changed
  def changed_content?(doc)
    return true if title != doc[:title] || content != doc[:content] || m[:tag_list] != doc[:metadata][:tag_list]
    false
  end
  
  # 
  def concept_similarity(doc)
    
  end
  
  # Create new document from given query
  # @param [String] did : unique ID
  #def self.create_from_query(did, doc)
  #  doc_db = Document.find_or_initialize_by_did(did)
  #  doc_db.update_attributes!(doc.merge(:source_id=>1, :basetime=>Time.now(), :metadata=>{}))
  #  doc_db
  #end
  
  def self.count_docs
    @count_docs ||= Item.all.size - find_all_by_itype([ITYPE_CONCEPT,'query'].flatten).size
  end
  
  
  def self.count_cons
    @count_cons ||= find_all_by_itype(ITYPE_CONCEPT).size
  end
  
  # Initialize new document
  def self.find_or_create(title, itype, o={})
    #debugger
    did = o[:did] || title.to_id
    item = Item.find_or_initialize_by_did(did)
    item.update_attributes!(o.merge(:title=>title, :did=>did, :itype=>itype, :source_id=>(o[:source_id] || 1), 
      :basetime=>(o[:basetime] || Time.now.in_time_zone(TIMEZONE))))
    item
  end

  def self.find_by_dids( dids )
    all(:conditions=>{:did=>dids})
  end
  
  def self.col_lists
    @@doc_cols  ||= columns.map{|e|e.name}
  end
  
  def self.itype_lists()
    @@itypes ||=  find(:all, :select=>'distinct(itype)').map{|e|e.itype}
  end
end

#Sunspot.setup(Item) do 
#   text :title, :content, :uri 
#   more_like_this :title, :content, :uri
#end

#Sunspot.setup(Item) do 
#   text :title, :content, :uri 
#   more_like_this do 
#      fields :title, :content, :uri 
#      min_document_frequency 10 
#      boost true 
#      max_query_terms 10 
#    end 
#end

app/controllers/items_controller.rb
require 'ddl_include'

class ItemsController < ApplicationController
  before_filter :authorize, :except => [:login, :index, :show_content, :search, :click]
  DL_TYPES = ['content','person','event','pubtime','caltime'].map{|e|e.to_sym}
  sidebar :search
  sidebar :filter
  sidebar :concept_cloud, :if=>:source_given?
  sidebar :relevant_concepts, :only=>:show, :if=>:item_concept?
  sidebar :linked_concepts, :only=>:show
  #sidebar :linked_documents, :only=>:show
  
  def source_given?
    params && params[:source]
  end

  # GET /items
  # GET /items.xml
  def index_old
    @start_at = params[:start_at] || Time.now.years_ago(1).to_date.to_s
    @end_at = params[:end_at] || (Date.tomorrow+1).to_s
    #@options = 
    conditions = {:hidden_flag=>false}
    conditions.merge!({:source_id=>params[:source]}) if params[:source] && !params[:source].include?("-1")
    conditions.merge!({:itype=>params[:itype]}) if params[:itype] && !params[:itype].include?("all")
    @items = Item.documents.between(@start_at, @end_at).paginate( :conditions=>conditions, :order=>"basetime desc", :page=>params[:page],:per_page=>50)
    #Item.all(:conditions=>["basetime > ?",Time.now - 86400], :order=>"basetime desc")
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @items }
    end
  end
  
  # GET /items
  # GET /items.xml
  def index
    redirect_to :action=>:search, :query=>TEXT_DUMMY, :order=>:recency, :doc_only=>true
  end
  
  # Process search action
  # - add query as item
  def search
    info params.inspect
    @query = params[:query]
    searcher = SolrSearcher.new
    @facet = {}
    @page_title = if @query == TEXT_DUMMY
      "All Documents"
    else
      "Search Result for '#{@query}'"
    end
    begin
      #debugger
      @search_results = searcher.process_request(@query, 'kwd', params.merge(:raw=>true))
      error "search_results : #{@search_results.inspect}"      
    rescue Exception => e
      error "Search failed!!", e
    end
    @rank_list = @search_results.hits.map{|e|{:item=>e.instance, :id=>e.instance.id, :score=>e.score}}
    @query_doc = Item.find_or_create(@query, 'query', :uri=>request.url, 
                   :content=>@rank_list.map{|e|e[:item].title}.join("\n"))

    @facet[:source_id] = searcher.process_request(@query, 'kwd', params.merge(:facet=>:source_id)).
                          find_all{|e|e.instance}.map{|e|["#{e.instance.title} (#{e.count})", e.value]}    

    @facet[:itype_str] = searcher.process_request(@query, 'kwd', params.merge(:facet=>:itype_str)).
                          map{|e|["#{e.value} (#{e.count})", e.value]}
    
    @facet[:basedate] = searcher.process_request(@query, 'kwd', params.merge(:facet=>:basedate)).
                          find_all{|e|Time.now - e.value < 86400*7}.map{|e|["#{e.value.to_date} (#{e.count})", e.value]}.reverse

    #debugger
    Item.metadata_fields(params[:facet_itype_str]).each do |field, type|
      @facet[field] = searcher.process_request(@query, 'kwd', params.merge(:facet=>field)).
                        map{|e|["#{e.value} (#{e.count})", e.value]}
    end
    #@docs = Item.find(@rank_list.map{|e|e[0]}).map_hash{|d|[d.id, d]}
    #debugger
  end
  
  # - Create History & Link
  # - Log pairwise preference 
  def click
    #debug(params)
    #process_click(params)
    src_item, tgt_item = params[:src_item_id].to_i, params[:id].to_i
    History.create(:htype=>params[:htype], :basetime=>Time.now, :src_item_id=>src_item, :item_id=>tgt_item, :user_id=>get_user_id(),
      :metadata=>{:position=>params[:position].to_i, :skipped_items=>params[:skipped_items], :url=>request.url})
    Link.find_or_create(src_item, tgt_item, 'c', :add=>1)
    #if ['con','doc'].include?(params[:htype]) && params[:skipped_items].split("|").size > 1
    #  searcher = SolrSearcher.new
    #  searcher.log_preference(params[:src_item_id].to_i, params[:htype] , params[:position].to_i)
    #  #search_remote('c', "#{params[:src_item_id]}|#{params[:skipped_items]}", :jtype=>'log')
    #end
    redirect_to :action=>:show, :id=>params[:id]
  end

  # GET /items/1
  # GET /items/1.xml
  def show
    searcher = SolrSearcher.new
    @item = Item.find(params[:id])
    @page_title = @item.title
    @link_docs, @link_cons = [], []
    $items = {}
    #debugger
    begin
      if @item.concept?
        @rel_cons = (searcher.process_request(@item.id, 'con', params) || [])[0..9]
      else
        #info "Ranklist(con) : #{@rel_cons.inspect}"
        @rel_docs = (searcher.process_request(@item.id, 'doc', params) || [])[0..9]
      end
      #info "Ranklist(doc) : #{@rel_docs.inspect}"
      #debugger
    rescue Exception => e
      error "Failed to get Ranklist!", e
      @rel_cons = []
      @rel_docs = []
    end
    #debugger
    @item.link_items.uniq.each do |e|
      (e.concept?)? (@link_cons << e) : (@link_docs << e)
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @item }
    end
  end
  
  # Show textual content of the document (for back-up)
  def show_content
    @item = Item.find(params[:id])
    render :action=>:show_content, :layout=>"content_only"
  end

  # GET /items/new
  # GET /items/new.xml
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.xml
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        flash[:notice] = 'Item was successfully created.'
        format.html { redirect_to(@item) }
        format.xml  { render :xml => @item, :status => :created, :location => @item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def create_concept
    case params[:source_type]
    when 'Tag'
      @tag = Tag.find(params[:source_id])
      @item = Item.find_or_create(@tag.title, 'concept')
      @tag.items.each do |item|
        Link.find_or_create(item.id, @item.id, 'u')
      end
      @tag.invalidate
    #when 'Document'
    #  @item = Item.find_or_create_concept(params[:])
    #  @concept = Concept.find(params[:source_id])
    when 'Query'
      content = Item.find(params[:checked_docs]).map{|e|e.to_s(true)}.join("\n") if !params[:checked_docs].blank?
      @item = Item.find_by_did(params[:query].to_id)
      params[:checked_docs].each do |dno|
        Link.find_or_create(dno.to_i, @item.id, 'u')
      end
    end
    redirect_to :controller=>'items', :action=>'show', :id=>@item.id
  end

  # PUT /items/1
  # PUT /items/1.xml
  def update
    @item = Item.find(params[:id])
    respond_to do |format|
      @item.replace_tags(params[:tags]) if !params[:tags].blank?
      if @item.update_attributes(params[:item].merge(:modified_flag=>true))
        flash[:notice] = 'Item was successfully updated.'
        format.html { redirect_to(item_url(@item)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.xml
  def destroy
    @item = Item.find(params[:id])
    @item.update_attributes!(:hidden_flag=>true)

    respond_to do |format|
      format.html { redirect_to(items_url) }
      format.xml  { head :ok }
    end
  end
  
  def links
    #debugger
    params[:order] ||= "content"
    conditions = {:batch=>params[:batch]} if params[:batch]
    @links = Link.paginate(:conditions=>conditions, :order=>"#{params[:order]} desc", :page=>params[:page], :per_page=>50)
  end
  
  def save_judgment
    params[:judgment].find_all{|k,v|v.size>0}.each do |e|
      Link.find(e[0]).update_attributes!(:judgment=>e[1])
    end
    params[:remark].find_all{|k,v|v.size>0}.each do |e|
      Link.find(e[0]).update_attributes!(:remark=>e[1])
    end
    redirect_to :action=>:links
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def select_for_itype(default)
    #options = case type
    #when 'Document' : ['webpage','email','pub','file']
    #when 'Concept' : ['person','concept']
    #when 'Query' : ['web','local']
		#end
    #select_tag(:itype, options_for_select(options.map{|e|[e,e]},default), 
    #  :multiple=>true, :onchange => 'this.form.submit()')
    options = ['all','webpage','email','pub','memo','news','blog','file','concept','query']
    select_tag(:itype, options_for_select(options.map{|e|[e,e]},default), 
      :multiple=>true, :onchange => 'this.form.submit()')
  end
  
  def select_for_facet(params, field_name)
    return "" if !@facet
    options = @facet[field_name.to_sym]
    param_name = "facet_#{field_name}".to_sym
    select_tag(param_name, options_with_all(field_name, params[param_name], options), :onchange => 'this.form.submit()')
  end
  
  def options_with_all(field_name, param, options)
    options_for_select([["<#{field_name.titleize}>", -1]].concat(options),param ? param.map{|e|e} : [-1])
  end
end

app/views/items/_linked_cons.html.erb
<div class="sidebar">
	<div class="title">Linked Concepts</div>
	<ul>
	<% @link_cons.find_all{|e|e.title != TEXT_DUMMY}[0..9].each do |c| %>
		<li> <%= link_to c.title[0..50], :action=>:show, :id=>c.id %> </li>
	<% end %>
	</ul>
</div>

app/views/items/_linked_docs.html.erb
<h2>Linked Documents</h2>
<table>
<% @link_docs[0..14].each do |item| %>
  <tr>
    <td width='80'><%= item.basetime.to_date %></td>
    <td><%= item.itype %></td>
    <td><%= link_to item.title, item_path(item), :title=>item.to_s %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Del', del_item_path(item) %></td>
  </tr>
<% end %>
</table>

app/views/items/_options.html.erb
<div class="sidebar">
  <div class="title">Options</div>
	<ul>
	<%= form_tag '', :method => 'GET' do %> 
		<li>Feedback? <%= check_box_tag :feedback, 'true', params['feedback'] , :onchange => 'this.form.submit()'%></li>
		<li>Context? <%= check_box_tag :context, 'true', params['context'] , :onchange => 'this.form.submit()'%></li>
		<% ContextVector.new.get.reverse[0...5].each do |c|%>
			<li><%="[#{c[:type]}] #{c[:query]}"%></li>
		<% end %>
	<% end %>
	</ul>
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<% form_for(@item, :url=>{:action=>:update, :id=>@item}) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %> : 
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :did %> : 
    <%= f.text_field :did %>
  </p>
  <p>
    <%= f.label :uri %> : 
    <%= f.text_field :uri %>
  </p>
  <p>
    <%= f.label :itype %> : 
    <%= f.text_field :itype %>
  </p>
	<p>
	  <b>Content:</b> <br>
	  <%= @item.content.gsub("\n","<br/>") if @item.content %>
	</p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<% content_for :left do %>
	<% debug(params)%>
	<% form_tag '', :method => 'GET'do %> 
	<h3>Source:</h3>
		<% options = options_for_select([['all',-1]].concat(Source.active.map{|e|[e.title, e.id]}),params[:source] ? params[:source].map{|e|e.to_i} : [-1]) %>
		<%= select_tag(:source, options, :multiple=>true, :onchange => 'this.form.submit()')%>
		<h3>Type:</h3>
		<%= select_for_itype(params[:itype])%><br>
		<h3>Period:</h3>
		<%= text_field_tag(:start_at, @start_at) %> ~ 
		<%= text_field_tag(:end_at, @end_at) %>
		<%= submit_tag('Filter') %>
	<% end %> 
<% end %>
<h1>Recent Documents</h1>
<table  class="sortable" id="sortabletable">
  <tr>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td width='70'><%= item.basetime.to_date %></td>
    <td><%= item.itype %></td>
    <td><%= link_to ((item.title.blank?)? "Untitled" : item.title) , item_path(item), :title=>item.to_s %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Del', del_item_path(item) %></td>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate(@items) if @items.respond_to?("total_pages")%>
<%= link_to 'New item', new_item_path %>

app/views/items/links.html.erb
<% content_for :left do %>
	<% debug(params)%>
	<% form_tag '', :method => 'GET'do %> 
		<h3>Sort By:</h3>
		<% options = options_for_select(DL_TYPES.map{|e|[e.to_s,e.to_s]} << ['judgment','judgment'], params[:order]) %>
		<%= select_tag(:order, options, :onchange => 'this.form.submit()')%>
		<h3>Batch:</h3>
		<%= text_field_tag(:batch, @batch) %>
		<%= submit_tag('Filter') %>
	<% end %> 
<% end %>
<% form_tag(:action=>"save_judgment", :method=>'post') do %>
<%= submit_tag("Submit Judgment")%>
<table class="sortable" id="sortabletable">
<tr>
  <th><%= "Calendar" %></th>
	<%= DL_TYPES.map{|e|"<th>#{e}</th>"}.join("\n") %>
  <th><%= "Email" %></th>
  <th  class="unsortable"> Judgment </th>
  <th  class="unsortable"> Remark </th>
</tr>
<% @links.each do |link| %>
  <tr>
    <td><%= link_to link.outdoc.title, link.outdoc, :title=>link.outdoc.to_s(true) %></td>
		<%= DL_TYPES.map{|e|"<td>#{fp(link.m[e])}</td>"}.join("\n") %>
    <td><%= link_to link.indoc.title,  link.indoc, :title=>link.indoc.to_s(true) %></td>
    <td><%= text_field_tag "judgment[#{link.id}]", link.judgment ,:size=>1 %></td>
    <td><%= text_field_tag "remark[#{link.id}]", link.remark ,:size=>5 %></td>
  </tr>
<% end %>
</table>
<%= submit_tag("Submit Judgment")%>
<% end %>

<br />
<%= will_paginate(@links)%>

app/views/items/new.html.erb
<h1>New item</h1>

<% form_for(@item, :url=>{:action=>:create}) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %> : 
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :did %> : 
    <%= f.text_field :did %>
  </p>
  <p>
    <%= f.label :uri %> : 
    <%= f.text_field :uri %>
  </p>
  <p>
    <%= f.label :itype %> : 
    <%= f.text_field :itype %>
  </p>
  <p>
    <%= f.label :remark %><br />
    <%= f.text_area :remark %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<%= form_tag :action => 'create_concept', :method => 'POST' do %> 
<table width='90%'>
  <tr>
  </tr>
	<% @rank_list.each do |e| %>
	  <tr>
	    <td><%= check_box_tag("checked_docs[]", e[:item].id) %><% e[:score].round_at(3) %></td>
	    <td><%= e[:item].itype %></td>
	    <td><%= link_to e[:item].title, {:controller=>'items', :action=>'click', :htype=>'kwd', :id=>e[:item].id, :src_item_id=>@query_doc.id} %></td>
	  </tr>
	<% end %>
</table>
<div class="pagination" align='center'>
  <%= will_paginate(@search_results.hits) %>
</div>
<%= hidden_field_tag "query", @query %>
<%= hidden_field_tag "source_type", 'Query' %>
<div align='right'><%= submit_tag 'Add Link'%></div>
<% end %>

<br />

app/views/items/show.html.erb
<% if @item.document? %>
	<iframe name='iframe_doc' src="<%= display_url(@item) %>" width="100%" height="80%" style="border: none;"></iframe>
	<% content_for :bottom do %>
		<%= render :partial => 'linked_docs' if @link_docs.size > 0 %>
		<h2>Relevant Documents</h2>
		<table class="sortable" id="sortabletable">
		<tr>
			<% header = ['time','type','title'] %>
			<% (header << 'score').concat(Searcher::DOC_FEATURES) if (Conf.debug || params[:debug]) %>
			<%= raw header.map{|f|"<td>#{f.to_s.capitalize}</td>"}%>
		</tr>
		<% @rel_docs.each_with_index do |e,i| %>
			<% item = cache_data("item_#{e[:id]}") %>
			<tr>
			  <td width='80'><%= item.basetime.to_date %></td>
			  <td><%= item.itype %></td>
			  <td><%= link_to item.title, {:controller=>'items', :action=>'click', :htype=>'doc', :id=>e[:id], :src_item_id=>@item.id, :position=>(i+1), :skipped_items=>@rel_docs[0..i].reverse.map{|e2|e2[:id]}.join("|")} %></td>
			<% if Conf.debug || params[:debug] %>
				<%=raw [:score].concat(Searcher::DOC_FEATURES).map{|f|"<td>#{(e[f]||0).to_f.r3}</td>"} %>
			<% end %>
			</tr>
			<% end %>
		</table>	
	<% end %>
<% else %>
	<%= render :partial => 'linked_docs' %>
<% end %>

app/views/items/show_content.html.erb
<p>
  <b>Metadata:</b> <br>
	<table border='1' cellspacing=0 cellpadding=2>
  <%= raw (@item.metadata||{}).find_all{|k,v|!v.blank?}.map{|e|"<tr><td>#{e[0]}</td><td>#{e[1]}</td></tr>"}.join("\n") %>
	</table>
</p>

<%= raw @item.content.gsub("\n","<br/>") if @item.content %>